cmake_minimum_required(VERSION 3.21)

get_filename_component(PLCOPEN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SOURCE_FILE "${PLCOPEN_ROOT}/doc/compliance/plcopen-motion-part1-io.yml")
set(OUTPUT_FILE "${PLCOPEN_ROOT}/doc/compliance/generated/plcopen-motion-part1-io.md")
set(ST_OUTPUT_FILE "${PLCOPEN_ROOT}/core/st/generated/mc_pins.h")

if(NOT EXISTS "${SOURCE_FILE}")
    message(FATAL_ERROR "Part 1 I/O source missing: ${SOURCE_FILE}")
endif()

file(READ "${SOURCE_FILE}" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(REPLACE "\n" ";" lines "${source}")

set(generated "# PLCopen Motion Control Part 1 I/O Declaration Matrix\n\n")
string(APPEND generated "> Generated from `plcopen-motion-part1-io.yml`; do not edit by hand.\n")
string(APPEND generated "> Normative names, directions and B/E levels follow Part 1 v2.0 Appendix B3.\n\n")
set(fb_count 0)
set(b_count 0)
set(e_count 0)
set(current_fb "")
set(current_variant "")
set(variant_names "")
set(variant_index 0)
set(seen_fbs ";")
set(seen_pins ";")
set(row_buffer "")
set(st_row_buffer "")
set(st_generated "#pragma once\n\nnamespace generated\n{\n\n")

macro(flush_fb)
    if(NOT "${current_fb}" STREQUAL "")
        string(APPEND generated "## ${current_fb}\n\n")
        string(APPEND generated "| Function block | Level | Direction | Pin | Supported | Comments |\n")
        string(APPEND generated "|---|---|---|---|---|---|\n")
        string(APPEND generated "${row_buffer}\n")
        math(EXPR fb_count "${fb_count} + 1")
        if(NOT "${st_row_buffer}" STREQUAL "")
            string(APPEND st_generated "inline constexpr PinDesc kPins${current_fb}[] = {\n${st_row_buffer}};\n\n")
        endif()
    endif()
    set(current_fb "")
    set(current_variant "")
    set(variant_names "")
    set(variant_index 0)
    set(seen_pins ";")
    set(row_buffer "")
    set(st_row_buffer "")
endmacro()

foreach(line IN LISTS lines)
    if(line MATCHES "^  - number:[ \t]*'3\\.[0-9]+'[ \t]*$")
        flush_fb()
    elseif("${current_fb}" STREQUAL "" AND line MATCHES "^    name:[ \t]*'([^']+)'[ \t]*$")
        set(current_fb "${CMAKE_MATCH_1}")
        if(seen_fbs MATCHES ";${current_fb};")
            message(FATAL_ERROR "Duplicate FB '${current_fb}' in ${SOURCE_FILE}")
        endif()
        string(APPEND seen_fbs "${current_fb};")
        set(current_variant "${current_fb}")
    elseif(NOT "${current_fb}" STREQUAL "" AND line MATCHES "^    variants:[ \t]*(.+)[ \t]*$")
        set(variant_names "${CMAKE_MATCH_1}")
        string(REPLACE "," ";" variant_names "${variant_names}")
        list(GET variant_names 0 current_variant)
    elseif(NOT "${current_fb}" STREQUAL "" AND line MATCHES "^      - \\{direction:[ \t]*(in_out|input|output),[ \t]*class:[ \t]*([BE]),[ \t]*name:[ \t]*([A-Za-z][A-Za-z0-9_]*)(,[ \t]*st_type:[ \t]*(AXIS_REF|BOOL|INT|DINT|LREAL|MC_BUFFER_MODE|MC_DIRECTION|MC_HOME_DIRECTION|MC_SWITCH_MODE))?(,[ \t]*binding:[ \t]*(metadata_only))?\\}[ \t]*$")
        set(direction "${CMAKE_MATCH_1}")
        set(level "${CMAKE_MATCH_2}")
        set(pin "${CMAKE_MATCH_3}")
        set(st_type "${CMAKE_MATCH_5}")
        set(binding_mode "${CMAKE_MATCH_7}")
        string(TOLOWER "${pin}" pin_key)
        if(seen_pins MATCHES ";${pin_key};")
            list(LENGTH variant_names variant_count)
            math(EXPR next_variant "${variant_index} + 1")
            if(variant_count LESS 2 OR NOT "${pin_key}" STREQUAL "axis" OR next_variant GREATER_EQUAL variant_count)
                message(FATAL_ERROR "Duplicate pin '${pin}' in ${current_fb}")
            endif()
            set(variant_index ${next_variant})
            list(GET variant_names ${variant_index} current_variant)
            set(seen_pins ";")
        endif()
        string(APPEND seen_pins "${pin_key};")
        if(level STREQUAL "B")
            math(EXPR b_count "${b_count} + 1")
        else()
            math(EXPR e_count "${e_count} + 1")
        endif()
        string(APPEND row_buffer "| ${current_variant} | ${level} | ${direction} | `${pin}` |  |  |\n")
        if(NOT "${st_type}" STREQUAL "" AND
           NOT "${binding_mode}" STREQUAL "metadata_only")
            if(st_type STREQUAL "AXIS_REF")
                set(cpp_type "axis_ref")
            elseif(st_type STREQUAL "BOOL")
                set(cpp_type "bool_")
            elseif(st_type STREQUAL "INT")
                set(cpp_type "int_")
            elseif(st_type STREQUAL "DINT")
                set(cpp_type "dint")
            elseif(st_type MATCHES "^MC_")
                set(cpp_type "dint")
                string(TOLOWER "${st_type}" nominal_name)
                set(nominal ", binding_type::${nominal_name}")
            else()
                set(cpp_type "lreal")
            endif()
            if(direction STREQUAL "output")
                set(is_input "false")
            else()
                set(is_input "true")
            endif()
            string(APPEND st_row_buffer
                   "    {\"${pin_key}\", Type::${cpp_type}, ${is_input}${nominal}},\n")
            set(nominal "")
        endif()
    elseif(line MATCHES "^[ \t]*$" OR line MATCHES "^#[ \t].*$" OR line MATCHES "^schema:[ \t]*plcopen-motion-part1-io-v1[ \t]*$" OR line MATCHES "^source:[ \t]*.+$" OR line MATCHES "^rows:[ \t]*$" OR line MATCHES "^    category:[ \t]*(single_axis|multi_axis)[ \t]*$" OR line MATCHES "^    pins:[ \t]*$")
    else()
        message(FATAL_ERROR "Unrecognized line in ${SOURCE_FILE}: '${line}'")
    endif()
endforeach()
flush_fb()
string(APPEND st_generated "} // namespace generated\n")

if(NOT fb_count EQUAL 43 OR NOT b_count EQUAL 235 OR NOT e_count EQUAL 297)
    message(FATAL_ERROR "Part 1 Appendix B3 totals mismatch: FB=${fb_count}/43 B=${b_count}/235 E=${e_count}/297")
endif()

if(PLCOPEN_UPDATE_GENERATED)
    get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_dir}")
    file(WRITE "${OUTPUT_FILE}" "${generated}")
    get_filename_component(st_output_dir "${ST_OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${st_output_dir}")
    file(WRITE "${ST_OUTPUT_FILE}" "${st_generated}")
else()
    if(NOT EXISTS "${OUTPUT_FILE}")
        message(FATAL_ERROR "Generated Part 1 I/O matrix missing: ${OUTPUT_FILE}")
    endif()
    file(READ "${OUTPUT_FILE}" existing)
    string(REPLACE "\r\n" "\n" existing "${existing}")
    if(NOT "${existing}" STREQUAL "${generated}")
        message(FATAL_ERROR "Generated Part 1 I/O matrix is stale. Run: cmake -DPLCOPEN_UPDATE_GENERATED=ON -P cmake/generate_part1_io_matrix.cmake")
    endif()
    if(NOT EXISTS "${ST_OUTPUT_FILE}")
        message(FATAL_ERROR "Generated ST MC pin table missing: ${ST_OUTPUT_FILE}")
    endif()
    file(READ "${ST_OUTPUT_FILE}" st_existing)
    string(REPLACE "\r\n" "\n" st_existing "${st_existing}")
    if(NOT "${st_existing}" STREQUAL "${st_generated}")
        message(FATAL_ERROR "Generated ST MC pin table is stale. Run: cmake -DPLCOPEN_UPDATE_GENERATED=ON -P cmake/generate_part1_io_matrix.cmake")
    endif()
endif()

message(STATUS "Part 1 I/O matrix synchronized (${fb_count} FBs, ${b_count} B, ${e_count} E)")
