cmake_minimum_required(VERSION 3.21)

get_filename_component(PLCOPEN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(SOURCE_FILE "${PLCOPEN_ROOT}/doc/compliance/plcopen-motion-v2-function-blocks.yml")
set(OUTPUT_FILE "${PLCOPEN_ROOT}/doc/compliance/generated/plcopen-motion-v2-function-blocks.md")

file(READ "${SOURCE_FILE}" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(REPLACE "\n" ";" lines "${source}")

set(generated "# PLCopen Motion Control Part 1/2 Generated Function-Block Matrix\n\n")
string(APPEND generated "> Generated from `plcopen-motion-v2-function-blocks.yml`; do not edit by hand.\n\n")
string(APPEND generated "| Category | Function block | Status | Standard row | Tests | KB |\n")
string(APPEND generated "|---|---|---|---|---|---|\n")

set(row_count 0)
set(in_rows OFF)
set(row_fb "")

macro(flush_row)
    if(NOT "${row_fb}" STREQUAL "")
        foreach(field IN ITEMS category status standard tests kb)
            if("${row_${field}}" STREQUAL "")
                message(FATAL_ERROR "Missing '${field}' for ${row_fb} in ${SOURCE_FILE}")
            endif()
        endforeach()

        set(standard_text "no")
        if("${row_standard}" STREQUAL "true")
            set(standard_text "yes")
        elseif(NOT "${row_standard}" STREQUAL "false")
            message(FATAL_ERROR "Invalid standard value '${row_standard}' for ${row_fb}")
        endif()

        set(kb_text "${row_kb}")
        if("${kb_text}" STREQUAL "-")
            set(kb_text "-")
        endif()

        string(APPEND generated "| ${row_category} | `${row_fb}` | `${row_status}` | ${standard_text} | `${row_tests}` | ${kb_text} |\n")
        math(EXPR row_count "${row_count} + 1")
    endif()

    set(row_fb "")
    set(row_category "")
    set(row_status "")
    set(row_standard "")
    set(row_tests "")
    set(row_kb "")
endmacro()

foreach(line IN LISTS lines)
    if(line MATCHES "^rows:[ \t]*$")
        set(in_rows ON)
    elseif(in_rows AND line MATCHES "^  - fb:[ \t]*(.+)$")
        flush_row()
        string(STRIP "${CMAKE_MATCH_1}" row_fb)
    elseif(in_rows AND NOT "${row_fb}" STREQUAL "" AND line MATCHES "^    ([A-Za-z_]+):[ \t]*(.*)$")
        set(key "${CMAKE_MATCH_1}")
        string(STRIP "${CMAKE_MATCH_2}" value)

        if(key STREQUAL "category")
            set(row_category "${value}")
        elseif(key STREQUAL "status")
            set(row_status "${value}")
        elseif(key STREQUAL "standard")
            set(row_standard "${value}")
        elseif(key STREQUAL "tests")
            set(row_tests "${value}")
        elseif(key STREQUAL "kb")
            set(row_kb "${value}")
        endif()
    endif()
endforeach()

flush_row()

if(row_count LESS 45)
    message(FATAL_ERROR "Expected at least 45 Part 1/2 rows, got ${row_count}")
endif()

if(PLCOPEN_UPDATE_GENERATED)
    get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_dir}")
    file(WRITE "${OUTPUT_FILE}" "${generated}")
else()
    if(NOT EXISTS "${OUTPUT_FILE}")
        message(FATAL_ERROR "Generated matrix missing: ${OUTPUT_FILE}")
    endif()

    file(READ "${OUTPUT_FILE}" existing)
    string(REPLACE "\r\n" "\n" existing "${existing}")

    if(NOT "${existing}" STREQUAL "${generated}")
        message(FATAL_ERROR "Generated matrix is stale. Run: cmake -DPLCOPEN_UPDATE_GENERATED=ON -P cmake/generate_part1_part2_matrix.cmake")
    endif()
endif()

message(STATUS "Part 1/2 function-block matrix is synchronized (${row_count} rows)")
