cmake_minimum_required(VERSION 3.21)

get_filename_component(PLCOPEN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(REPLAY_DIR "${PLCOPEN_ROOT}/testdata/replay")
set(MANIFEST "${REPLAY_DIR}/manifest.json")

function(plcopen_json_get output json)
    string(JSON value ERROR_VARIABLE json_error GET "${json}" ${ARGN})
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR "JSON get failed at '${ARGN}': ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(plcopen_json_type output json)
    string(JSON value ERROR_VARIABLE json_error TYPE "${json}" ${ARGN})
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR "JSON type failed at '${ARGN}': ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(plcopen_json_length output json)
    string(JSON value ERROR_VARIABLE json_error LENGTH "${json}" ${ARGN})
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR "JSON length failed at '${ARGN}': ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "Replay manifest missing: ${MANIFEST}")
endif()

file(READ "${MANIFEST}" manifest)

plcopen_json_get(schema "${manifest}" schema)
if(NOT schema STREQUAL "plcopen-golden-replay-manifest-v1")
    message(FATAL_ERROR "Unexpected replay manifest schema: ${schema}")
endif()

plcopen_json_type(fixtures_type "${manifest}" fixtures)
if(NOT fixtures_type STREQUAL "ARRAY")
    message(FATAL_ERROR "Replay manifest 'fixtures' must be an array")
endif()

plcopen_json_length(fixture_count "${manifest}" fixtures)
if(fixture_count LESS 3)
    message(FATAL_ERROR "Expected at least 3 manifest fixtures, got ${fixture_count}")
endif()

math(EXPR fixture_last_index "${fixture_count} - 1")
set(manifest_ids "")
set(manifest_paths "")

foreach(index RANGE 0 ${fixture_last_index})
    foreach(field IN ITEMS id path source coverage)
        plcopen_json_type(field_type "${manifest}" fixtures ${index} ${field})
        if(field STREQUAL "coverage")
            if(NOT field_type STREQUAL "ARRAY")
                message(FATAL_ERROR "Replay manifest fixture ${index} coverage must be an array")
            endif()
        elseif(NOT field_type STREQUAL "STRING")
            message(FATAL_ERROR "Replay manifest fixture ${index} ${field} must be a string")
        endif()
    endforeach()

    plcopen_json_get(id "${manifest}" fixtures ${index} id)
    plcopen_json_get(path "${manifest}" fixtures ${index} path)

    if(NOT path MATCHES "^[A-Za-z0-9_.-]+\\.jsonl$")
        message(FATAL_ERROR "Replay manifest fixture '${id}' has unsupported path '${path}'")
    endif()
    if(NOT EXISTS "${REPLAY_DIR}/${path}")
        message(FATAL_ERROR "Replay manifest fixture '${id}' is missing file '${path}'")
    endif()

    list(APPEND manifest_ids "${id}")
    list(APPEND manifest_paths "${path}")
endforeach()

foreach(required IN ITEMS format-smoke-single-axis format-smoke-two-axis format-smoke-stop)
    list(FIND manifest_ids "${required}" required_index)
    if(required_index EQUAL -1)
        message(FATAL_ERROR "Replay manifest does not define required fixture '${required}'")
    endif()
endforeach()

file(GLOB replay_files RELATIVE "${REPLAY_DIR}" "${REPLAY_DIR}/*.jsonl")
list(LENGTH replay_files replay_count)

if(replay_count LESS 3)
    message(FATAL_ERROR "Expected at least 3 replay fixture files, got ${replay_count}")
endif()

set(line_count 0)

foreach(path IN LISTS replay_files)
    list(FIND manifest_paths "${path}" manifest_index)
    if(manifest_index EQUAL -1)
        message(FATAL_ERROR "Replay fixture file is not listed in manifest: ${path}")
    endif()

    set(file "${REPLAY_DIR}/${path}")
    file(READ "${file}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(REPLACE "\n" ";" lines "${content}")

    set(file_line_count 0)
    foreach(line IN LISTS lines)
        if(line STREQUAL "")
            continue()
        endif()

        math(EXPR file_line_count "${file_line_count} + 1")
        math(EXPR line_count "${line_count} + 1")

        foreach(field IN ITEMS tick axis position velocity acceleration)
            plcopen_json_type(field_type "${line}" ${field})
            if(NOT field_type STREQUAL "NUMBER")
                message(FATAL_ERROR "testdata/replay/${path} line ${file_line_count} '${field}' must be a number")
            endif()
        endforeach()

        foreach(field IN ITEMS tick axis)
            plcopen_json_get(value "${line}" ${field})
            if(NOT value MATCHES "^-?[0-9]+$")
                message(FATAL_ERROR "testdata/replay/${path} line ${file_line_count} '${field}' must be an integer")
            endif()
        endforeach()

        plcopen_json_type(source_type "${line}" source)
        if(NOT source_type STREQUAL "STRING")
            message(FATAL_ERROR "testdata/replay/${path} line ${file_line_count} 'source' must be a string")
        endif()
        plcopen_json_get(source "${line}" source)
        if(source STREQUAL "")
            message(FATAL_ERROR "testdata/replay/${path} line ${file_line_count} 'source' must not be empty")
        endif()
    endforeach()

    if(file_line_count EQUAL 0)
        message(FATAL_ERROR "testdata/replay/${path} has no replay samples")
    endif()
endforeach()

message(STATUS "Replay fixtures verified (${replay_count} files, ${line_count} samples)")
