# Structural closure check for doc/compliance/st-feature-set.yml.
# This parser intentionally accepts only the repository's compact schema; it
# is not a general YAML reader.  Keeping it dependency-free lets every CTest
# platform validate the same manifest.

cmake_minimum_required(VERSION 3.21)

get_filename_component(PLCOPEN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(FEATURE_SET "${PLCOPEN_ROOT}/doc/compliance/st-feature-set.yml")
if(NOT EXISTS "${FEATURE_SET}")
    message(FATAL_ERROR "missing ${FEATURE_SET}")
endif()

file(STRINGS "${FEATURE_SET}" LINES)
file(READ "${FEATURE_SET}" FEATURE_TEXT)
if(NOT FEATURE_TEXT MATCHES "^schema: plcopen-st-feature-set-v1[\r\n]")
    message(FATAL_ERROR "unexpected ST feature-set schema")
endif()
set(REQUIRED_SETS grammar types operators conversions pous storage tasks
                  sfc_qualifiers functions fbs pins diagnostics)
set(SEEN_SETS)
set(SEEN_KEYS)
set(FAILURES)
set(PENDING_COUNT 0)
set(ITEM_COUNT 0)
set(FUNCTION_COUNT 0)
set(FB_EXPECTED_TOTAL 0)
set(CURRENT_SET "")
set(ENTRY_ID "")
set(ENTRY_STATUS "")
set(ENTRY_TEST "")
set(ENTRY_SPEC "")
set(ENTRY_SOURCE "")
set(ENTRY_SCOPE "")
set(ENTRY_REJECTION "")
set(ENTRY_EXPECTED "")
set(ENTRY_ITEMS "")

macro(resolve_reference reference out)
    if("${reference}" MATCHES "^(core|cmake|doc|testdata)/")
        set(${out} "${PLCOPEN_ROOT}/${reference}")
    else()
        set(${out} "${PLCOPEN_ROOT}/doc/compliance/${reference}")
    endif()
endmacro()

macro(flush_entry)
    if(NOT ENTRY_ID STREQUAL "")
        math(EXPR ITEM_COUNT "${ITEM_COUNT} + 1")
        set(key "${CURRENT_SET}:${ENTRY_ID}")
        if(key IN_LIST SEEN_KEYS)
            list(APPEND FAILURES "duplicate item ${key}")
        else()
            list(APPEND SEEN_KEYS "${key}")
        endif()
        if(ENTRY_STATUS STREQUAL "pending")
            math(EXPR PENDING_COUNT "${PENDING_COUNT} + 1")
            if(ENTRY_SPEC STREQUAL "")
                list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: pending item lacks spec")
            endif()
        elseif(ENTRY_STATUS STREQUAL "implemented")
            if(ENTRY_TEST STREQUAL "")
                list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: implemented item lacks test")
            endif()
        elseif(ENTRY_STATUS STREQUAL "excluded")
            if(ENTRY_SCOPE STREQUAL "" OR ENTRY_REJECTION STREQUAL "" OR
               ENTRY_REJECTION STREQUAL "pending")
                list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: excluded item lacks scope_reason/rejection_test")
            endif()
        else()
            list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: invalid status '${ENTRY_STATUS}'")
        endif()

        foreach(field IN ITEMS ENTRY_TEST ENTRY_SPEC ENTRY_SOURCE)
            if(NOT "${${field}}" STREQUAL "")
                resolve_reference("${${field}}" path)
                if(NOT EXISTS "${path}")
                    list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: missing ${${field}}")
                endif()
            endif()
        endforeach()
        if(ENTRY_STATUS STREQUAL "excluded" AND
           NOT ENTRY_REJECTION STREQUAL "pending")
            resolve_reference("${ENTRY_REJECTION}" path)
            if(NOT EXISTS "${path}")
                list(APPEND FAILURES "${CURRENT_SET}.${ENTRY_ID}: missing ${ENTRY_REJECTION}")
            endif()
        endif()

        if(CURRENT_SET STREQUAL "functions")
            math(EXPR FUNCTION_COUNT "${FUNCTION_COUNT} + 1")
        endif()
        if(CURRENT_SET STREQUAL "fbs" AND NOT ENTRY_EXPECTED STREQUAL "")
            math(EXPR FB_EXPECTED_TOTAL "${FB_EXPECTED_TOTAL} + ${ENTRY_EXPECTED}")
            if(NOT ENTRY_ITEMS STREQUAL "")
                string(REGEX REPLACE "^\\[|\\]$" "" item_text "${ENTRY_ITEMS}")
                string(REPLACE ", " ";" item_list "${item_text}")
                list(LENGTH item_list actual_count)
                if(NOT actual_count EQUAL ENTRY_EXPECTED)
                    list(APPEND FAILURES "fbs.${ENTRY_ID}: expected ${ENTRY_EXPECTED} items, got ${actual_count}")
                endif()
            endif()
        endif()
    endif()
    set(ENTRY_ID "")
    set(ENTRY_STATUS "")
    set(ENTRY_TEST "")
    set(ENTRY_SPEC "")
    set(ENTRY_SOURCE "")
    set(ENTRY_SCOPE "")
    set(ENTRY_REJECTION "")
    set(ENTRY_EXPECTED "")
    set(ENTRY_ITEMS "")
endmacro()

foreach(line IN LISTS LINES)
    if(line MATCHES "^([a-z_]+):$")
        set(candidate "${CMAKE_MATCH_1}")
        flush_entry()
        if(candidate IN_LIST REQUIRED_SETS)
            set(CURRENT_SET "${candidate}")
            list(APPEND SEEN_SETS "${candidate}")
        else()
            set(CURRENT_SET "")
        endif()
    elseif(NOT CURRENT_SET STREQUAL "" AND
           line MATCHES "^  - \\{id: ([^,}]+), status: ([^,}]+)(.*)\\}$")
        set(item_id "${CMAKE_MATCH_1}")
        set(item_status "${CMAKE_MATCH_2}")
        set(item_tail "${CMAKE_MATCH_3}")
        flush_entry()
        set(ENTRY_ID "${item_id}")
        set(ENTRY_STATUS "${item_status}")
        set(tail "${item_tail}")
        foreach(field IN ITEMS test spec source scope_reason rejection_test expected_count)
            if(tail MATCHES ", ${field}: ([^,}]+)")
                if(field STREQUAL "scope_reason")
                    set(ENTRY_SCOPE "${CMAKE_MATCH_1}")
                elseif(field STREQUAL "rejection_test")
                    set(ENTRY_REJECTION "${CMAKE_MATCH_1}")
                elseif(field STREQUAL "expected_count")
                    set(ENTRY_EXPECTED "${CMAKE_MATCH_1}")
                else()
                    string(TOUPPER "${field}" upper)
                    set("ENTRY_${upper}" "${CMAKE_MATCH_1}")
                endif()
            endif()
        endforeach()
        flush_entry()
    elseif(NOT CURRENT_SET STREQUAL "" AND line MATCHES "^  - id: (.+)$")
        set(item_id "${CMAKE_MATCH_1}")
        flush_entry()
        set(ENTRY_ID "${item_id}")
    elseif(NOT ENTRY_ID STREQUAL "" AND line MATCHES "^    ([a-z_]+): (.+)$")
        set(field "${CMAKE_MATCH_1}")
        set(value "${CMAKE_MATCH_2}")
        if(field STREQUAL "status")
            set(ENTRY_STATUS "${value}")
        elseif(field STREQUAL "test")
            set(ENTRY_TEST "${value}")
        elseif(field STREQUAL "spec")
            set(ENTRY_SPEC "${value}")
        elseif(field STREQUAL "source")
            set(ENTRY_SOURCE "${value}")
        elseif(field STREQUAL "scope_reason")
            set(ENTRY_SCOPE "${value}")
        elseif(field STREQUAL "rejection_test")
            set(ENTRY_REJECTION "${value}")
        elseif(field STREQUAL "expected_count")
            set(ENTRY_EXPECTED "${value}")
        elseif(field STREQUAL "items")
            set(ENTRY_ITEMS "${value}")
        endif()
    endif()
endforeach()
flush_entry()

foreach(required IN LISTS REQUIRED_SETS)
    if(NOT required IN_LIST SEEN_SETS)
        list(APPEND FAILURES "missing required set ${required}")
    endif()
endforeach()
list(REMOVE_DUPLICATES SEEN_SETS)
list(LENGTH SEEN_SETS SET_COUNT)
if(NOT SET_COUNT EQUAL 12)
    list(APPEND FAILURES "expected 12 required sets, got ${SET_COUNT}")
endif()
if(NOT FUNCTION_COUNT EQUAL 51)
    list(APPEND FAILURES "functions: expected 51 entries, got ${FUNCTION_COUNT}")
endif()
if(NOT FB_EXPECTED_TOTAL EQUAL 134)
    list(APPEND FAILURES "fbs: expected total 134, got ${FB_EXPECTED_TOTAL}")
endif()
if(REQUIRE_COMPLETE AND NOT PENDING_COUNT EQUAL 0)
    list(APPEND FAILURES "feature set is incomplete: ${PENDING_COUNT} pending items")
endif()

if(FAILURES)
    string(REPLACE ";" "\n" text "${FAILURES}")
    message(FATAL_ERROR "ST feature-set check failed:\n${text}")
endif()
message(STATUS "ST feature-set verified: ${SET_COUNT} sets, ${ITEM_COUNT} items, ${PENDING_COUNT} pending")
