vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO lusipad/plcopen
    REF v0.20.0
    SHA512 B507A8FAD28072004BFC51EC8B1C9AF55616B117B093FE10343A1D123FD85DA5856B9BC583B801C8F8DB6CBCA9ED53E3F72AEB5DFD3C7E18F3537A63F206B619
    HEAD_REF main
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_TESTING=OFF
        -DPLCOPEN_BUILD_DEMOS=OFF
        -DPLCOPEN_BUILD_DOCS=OFF
        -DPLCOPEN_BUILD_PYTHON_BINDINGS=OFF
        -DPLCOPEN_BUILD_TESTS=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME plcopen CONFIG_PATH lib/cmake/plcopen)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
